# Generated by Django 5.2.8 on 2025-11-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('nivel', models.IntegerField(default=1)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
